### 
GET http://localhost:8080/products

### obteenmos los productos de la pagina 2
GET http://localhost:8080/products?page=2

### buscamos por nombre
http://localhost:8080/products?query=lejía&page=1

### Get product by id
GET http://localhost:8080/products/1

### Create product
POST http://localhost:8080/products
Content-Type: application/json

{
  "id": 133,
  "productName": "Perros Salchicha",
  "productDescription": "Perros salchicha congelados",
  "stockQuantity": 25,
  "category": "CONGELADOS",
  "barCode": "6c0a271d-c3b4-4a5a-8c90-57f858ec8267",
  "imageUrl": "https://source.unsplash.com/480x300/?hotdogs",
  "price": 5.00,
  "active": 1
}

### delete product
DELETE http://localhost:8080/products/5

### Update product
PUT http://localhost:8080/products
Content-Type: application/json

{
	"id": 5,
  "productName": "Leche descremada",
  "imageUrl": "https://source.unsplash.com/480x300/?milk&random=1"
}
